import { FormField } from "../../../types/form";

export const FORM_FIELDS: FormField[] = [
  {
    key: "name",
    label: "Name",
    type: "text",
    required: true,
    placeholder: "Enter your full name",
    pattern: undefined,
  },
  {
    key: "userName",
    label: "User Name",
    type: "text",
    required: true,
    placeholder: "Choose a username",
    pattern: undefined,
  },
  {
    key: "email",
    label: "Email",
    type: "email",
    required: true,
    placeholder: "Enter your email address",
    pattern: undefined,
  },
  {
    key: "password",
    label: "Password",
    type: "password",
    required: true,
    placeholder: "Enter your password",
    pattern: undefined,
  },
  {
    key: "dateOfBirth",
    label: "Date of Birth",
    type: "date",
    required: true,
    placeholder: "Select your date of birth",
    pattern: undefined,
  },
  {
    key: "presentAddress",
    label: "Present Address",
    type: "text",
    required: true,
    placeholder: "Enter your current address",
    pattern: undefined,
  },
  {
    key: "permanentAddress",
    label: "Permanent Address",
    type: "text",
    required: true,
    placeholder: "Enter your permanent address",
    pattern: undefined,
  },
  {
    key: "city",
    label: "City",
    type: "text",
    required: true,
    placeholder: "Enter your city",
    pattern: undefined,
  },
  {
    key: "postalCode",
    label: "Postal Code",
    type: "text",
    required: true,
    placeholder: "Enter postal code",
    pattern: undefined,
  },
  {
    key: "country",
    label: "Country",
    type: "text",
    required: true,
    placeholder: "Enter your country",
    pattern: undefined,
  },
];
